### ISSUE TITLE
Needs work

### ISSUE THREAD

**Issue by zachnewburgh** [learn-co-curriculum/using-bundler#25]
I've loved the written tutorials, labs, etc., thus far, but this one was challenging to decipher. I understand what gems are (at least, I think I do), but I'm still unclear on how they're implemented. I don't feel like I've yet mastered this skill like I was able after completing the other lessons.

Here are some areas that I'd highlight for improvement:

(i) Explanation for what the code provided means/does;
(ii) Why is the syntax written in the way that it is? What does each part of the code block/hash mean? What is a twiddle-wakka? Why is it used?
(iii) What is the hash argument vs. block syntax when used for bundling gems?
(iv) What is a "group"? What does a "group" do?
(v) How can one link a gem to a remote repository?
(vi) What is the purpose of the following code in config/environment.rb?

```
require 'bundler/setup'
Bundler.require(:default, :development)
```

Thanks for giving this some thought :)

**Comment by AnnJohn** [comment]
thanks for the great suggestions @zachnewburgh. At the moment, we're not making major updates to curriculum but will do a heavy round of revisions soon and will incorporate your points. thanks again!
