### ISSUE TITLE
problem with Windows line endings

### ISSUE THREAD

**Issue by jnoconor** [learn-co-curriculum/using-bundler#34]
A student on a Windows operating system using the Learn IDE had issues with this test:

```ruby
    it "should list the hashie gem without specifying a version" do
      expect(@gemfile_text =~ /gem .hashie.$/).not_to eq(nil)
    end
```

The reason was that the Gemfile had Windows line endings: `\r\n` instead of just `\n`. I had the student edit the spec file as a workaround. There is probably some way to accommodate both Windows and non-Windows users.

**Comment by SophieDeBenedetto** [comment]
fixed with cross-platform end-of-line regex 9fa5f24a4e00c3638cee16c218d2f73821171437
