### ISSUE TITLE
this is a code along but as constructed - tests dont pass from directions in writeup

### ISSUE THREAD

**Issue by bmolina-nyc** [learn-co-curriculum/using-bundler#36]
The two specs in the groups section don't pass from the direction in the write along.

It's easy enough to figure out test 8 on your own 

group :test do
  gem 'rspec'
end

but test 7 syntax isn't covered in the lesson and takes some confusing googling to figure out what works - moreover, the lesson tells you to enter the below into your gemfile - so this is presumably what would make test 7 pass,.....

group :development do
  gem "pry"
end

but to get  test 7 to pass, the above needs to be removed and re-written as 
gem "pry", :group => "development"   .  As this was a code along, I thought this was a bit confusing since no direction about hash formatting was explicitly covered. It's also strange to be directed to type something in so I spent a long time playing with this before realizing it had to be deleted.

**Comment by SophieDeBenedetto** [comment]
thanks for your feedback. I added some notes to the README to clear that up
