### ISSUE TITLE
Gem groups causing rspec failures

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/using-bundler#4]
Running the test suite silently adds a `.bundle/config` file, which consistently causes at least 3 tests to fail. This can be especially confusing as it is not discoverable after the first time ran. I'm not able to track down which line is doing it (49?)

**Comment by spencer1248** [comment]
This could possibly be due to the new version of bundler released.

**Comment by sammarcus** [comment]
I tried against 1.9.9, 10.1 and no luck. Which version is definitely a safe bet?

**Comment by spencer1248** [comment]
No clue unfortunately. Maybe @SophieDeBenedetto or @deniznida can look at it?

**Comment by deniznida** [comment]
Just tested this, it is creating the `.bundle/config` file but the tests are all passing. I'm using Bundler version 1.9.9

**Comment by changamanda** [comment]
@deniznida @sammarcus @spencer1248 Fixed this today
