### ISSUE TITLE
they moved the awesome_print repository 

### ISSUE THREAD

**Issue by lqf2b8** [learn-co-curriculum/using-bundler#45]
so in the solution line 6 of the Gemfile needs to be updated to read gem "awesome_print", git: "https://github.com/awesome-print/awesome_print"

**Comment by gj** [comment]
This is just a matter of syncing the solution branches for `-students` and `-curriculum`. Change was made to `-curriculum` in August.

cc: @cjbrock @aturkewi @AnnJohn

**Comment by pickledyamsman** [comment]
@aturkewi this is still an issue and @gj 's comment should fix it!

**Comment by aturkewi** [comment]
Thanks for letting me know all! Just re-deployed the lab and it should be synced now :)
