### ISSUE TITLE
Hashie Gem

### ISSUE THREAD

**Issue by Scyntre2017** [learn-co-curriculum/using-bundler#49]
The test was allowed to pass without specifying the gem "hashie" in the Gemfile file, up until the point it needed it in the run.rb file.
![screenshot from 2017-07-19 05-32-17](https://user-images.githubusercontent.com/24966803/28360572-de0e4eb8-6c43-11e7-88bd-63de0af24894.png)

![screenshot from 2017-07-19 05-26-01](https://user-images.githubusercontent.com/24966803/28360468-8218a3ba-6c43-11e7-9d2f-560ceae23638.png)

**Comment by aviflombaum** [comment]
Ya, the regex we are using for that isn't great. Fixing now.

**Comment by aviflombaum** [comment]
Fixed. @gj b77baa9cf3b6cea6c25e08004384d2aecd391e34

![Regex](https://dl.dropboxusercontent.com/s/5jtojznw6lc5ygl/2017-07-19%20at%208.16%20AM.png)

![Broken](https://dl.dropboxusercontent.com/s/dx8a1ex2c1avp6i/2017-07-19%20at%208.17%20AM.png)
