### ISSUE TITLE
ruby-toolbox.com is now a barebones site

### ISSUE THREAD

**Issue by vsparrow** [learn-co-curriculum/using-bundler#51]
Affects section: 
HOW TO FIND A GEM?

From ruby-toolbox:
"The server hosting The Ruby Toolbox went bust on the evening of June 7th. While I do have backups, the original source code is in a very outdated state so I currently don't feel it makes sense to try and get it running again."

Experience
The learning experience is not affected by ruby-toolbox being up or down since there are pictures, but I thought I would inform.

Thanks

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the notice. We updated the README with an alternate resource to search for Ruby gems.

As always, thanks for contributing! 💙
