### ISSUE TITLE
Awesome Print test should specify SSH URL

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/using-bundler#55]
The test for the Awesome Print gem should specify that it expects the SSH URL, not the HTTPS URL. I've come across numerous students who had no idea why the test wasn't passing with the HTTPS URL, and it can be difficult (especially for novices) to understand the regex.

https://github.com/learn-co-curriculum/using-bundler/blob/2c7f7332e457f3e4c30203f61ca1c1d7ac1f108c/spec/bundler_spec.rb#L40-L43

**Comment by drakeltheryuujin** [comment]
Test updated. Thanks for your feedback! 💙
