### ISSUE TITLE
Gems Using Remote Git Repository

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/using-bundler#62]
Hey, it would be really helpful if there was an explanation of how to include a gem from an external source. The lesson didn't explain it, requires this for the lab: `should list the awesome_print gem specifying a remote git repository (use github) (FAILED - 1)` and then says "Top Tip: Use SSH syntax for the AwesomePrint Gem." I can't very well use SSH if I don't even know how to complete the task on a basic level.

Thanks, guys.

**Comment by helloamandamurphy** [comment]
Additionally there's no explanation of what a twiddle wakka is in the ReadMe, and then it's requested in the lab.

**Comment by helloamandamurphy** [comment]
There's nothing in the ReadMe that would suggest that this was how to write this code `gem 'awesome_print', git: "git@github.com:awesome-print/awesome_print.git"` This information needs to be included in the lesson.

**Comment by sgharms** [comment]
Thanks for the notes. Adjusted.
