### ISSUE TITLE
Tests have end-of-line char in regex for 'hashie' gem which causes bug

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/using-bundler#64]
__Summary:__ Students are not passing tests with correct code because `hashie gem` test fails. This is caused by an end-of-line character (`$`) in the regex of the specfile (line 27 of `bundler_spec.rb`).

__Solution:__ Delete `$` inside regex on line 27 of `bundler_spec.rb`.

**Comment by maxwellbenton** [comment]
Hi @micahshute,

Fixed in master and rebased into solution. Thank you!
