### ISSUE TITLE
Regex too specific?

### ISSUE THREAD

**Issue by drewprice** [learn-co-curriculum/using-bundler#9]
The following test fails (and all others pass) if the arguments are passed in in opposite order, i.e. ```Bundler.require(:development, :default)```

* Bundler integration should require the default and development groups in the environment
```ruby
     Failure/Error: expect(@environment_text =~ /Bundler\.require\(:default, :development\)/).not_to eq(nil)
       
       expected: value != nil
            got: nil
       
       (compared using ==)
     # ./spec/bundler_spec.rb:99:in `block (3 levels) in <top (required)>'
```

**Comment by AnnJohn** [comment]
@SophieDeBenedetto due by 8/21
